import raw from '../../data/driving-bans/canonical.json' with { type: 'json' };
import { dajcEuropeCoverage } from '../europe-coverage.mjs';
import { hydrateCanonical, validateCanonical, snapshot, calendarRules } from '../../src/lib/driving-bans/core.mjs';
export const canonicalDrivingBans = hydrateCanonical(raw, dajcEuropeCoverage);
validateCanonical(canonicalDrivingBans, dajcEuropeCoverage);
export const drivingBanCalendars = calendarRules(canonicalDrivingBans);
export const getDrivingBansSnapshot = (now = new Date()) => snapshot(canonicalDrivingBans, dajcEuropeCoverage, now);
export const getCalendarById = id => drivingBanCalendars.find(rule => rule.id === id);
export const restrictionTypesOf = rule => Array.isArray(rule.restrictionTypes) ? rule.restrictionTypes : (rule.restriction_types || ['general']);
export const matchesRestrictionType = (rule, type = 'all') => type !== 'general' || restrictionTypesOf(rule).includes('general');
